CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

CFLAGS = -mcpu=cortex-m3 -mthumb -O0 -Wall -ffreestanding
LDFLAGS = -T ld/stm32f103.ld -nostdlib

SRC = src/main.c startup/startup_stm32f103.s
OBJ = build/main.o build/startup.o

TARGET = build/firmware.elf
BIN = build/firmware.bin

all: $(TARGET)

build:
	mkdir -p build

build/main.o: src/main.c | build
	$(CC) $(CFLAGS) -c $< -o $@

build/startup.o: startup/startup_stm32f103.s | build
	$(CC) $(CFLAGS) -c $< -o $@

$(TARGET): build/main.o build/startup.o
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@
	$(OBJCOPY) -O binary $@ $(BIN)
	$(SIZE) $@

flash: $(TARGET)
	st-flash write $(BIN) 0x8000000

clean:
	rm -rf build
